#!/usr/bin/env python
import sys
import os
import getopt
from lib.output import Output
from lib.options import Options
from lib.application import Application

def main(argv):

	options = Options()
	options.setVars(argv)

	app = Application()
	app.configure(options.config)
		


if __name__ == "__main__":
	main(sys.argv[1:])
